name: Image Builder
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

  jobs:
    build:
      steps:
        - uses: actions/checkout@v3

        - name: build
          run: make docker-build 

        - name: Connect Tailscale
          uses: tailscale/github-action@v2
          with:
            oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
            oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
            tags: "tag:ci"
            version: 1.52.0

        - name: push
          run: make docker-push

        - name: restart
          run: make restart-app
